platform :ios do

  # circumvent provisioning profile errors by setting name explicitly using provisioing_profile
  # option as outline in this ticket: https://github.com/bamlab/fastlane-plugin-cordova/issues/15

  desc "Build debug version and install on connected device"
  lane :install do
    build_debug
    install_only
  end

  desc "Build release version and upload to testflight"
  lane :beta do
    build_release
    update_generated_project
    testflight(
      ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'],
    )
  end


  lane :build_debug do
    match(
      type: "development",
    )
    provProfile = ENV["sigh_#{ENV['APP_IDENTIFIER']}_development"];
    cordova(
      platform: 'ios',
      provisioning_profile: provProfile,
      release: false,
      type: 'development'
    )
  end

  lane :install_only do
    install_on_device(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end

  lane :build_release do
    match(
      type: 'appstore',
    )
    provProfile = ENV["sigh_#{ENV['APP_IDENTIFIER']}_appstore"];
    cordova(
      platform: 'ios',
      provisioning_profile: provProfile,
      build_number: latest_testflight_build_number + 1,
      release: true,
      type: 'appstore'
    )
  end

  lane :update_generated_project do
    set_info_plist_value(path: 'platforms/ios/' + ENV['APP_NAME'] + '/' + ENV['APP_NAME'] + '-Info.plist', key: "NSCameraUsageDescription", value: "This app requires camera access to function properly.")
  end

end
